service: sls-example

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless

functions:
  is-alive:
    handler: is-alive.isAlive
    events:
      - http:
          path: johnny5
          method: get
